#!/bin/bash

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

a=dotfiles
b=@riyuzenn
c=os
d="$(uname -s)"
e=sh
f=$(basename $SHELL)
colors=$(for i in {0..7}; do echo -en "\e[${1}$((30 + $i))m▁▁▁"; done)

tput clear
cat << EOF
   ${f5}.${f3}-${f1}^${t}${f3}-${f5}.     $f6$a $t~ $b
  ${f6}/${f7}_${f6}/${f7}_${f6}\\${f7}_${f6}\    $f6$e $t~ $f 
 ${f4}' ' ${f1}J${f4} ' ' 
$colors

EOF

create_env() {
   echo "I: Creating directories"
   mkdir -p $HOME/.config/
   mkdir -p $HOME/.local/bin/
   mkdir -p $HOME/.local/share/fonts/
   mkdir -p $HOME/wallpapers/
   echo "S: Directories successfully created"
}

copy_cfg() {
   echo  "I: Copying dotfiles, this may take a while..."
   cp -r ./msc/fonts/* $HOME/.local/share/fonts/
   cp -r ./msc/bin/* $HOME/.local/bin/ 2> /dev/null
   cp -r  ./cfg/* $HOME/.config/
   cp -r ./msc/{.Xresources,.xinitrc,.zshrc} $HOME
   cp -r ./images/* $HOME/wallpapers/
   echo
   echo "S: All configurations were successfully copied"
   echo "Enjoy ricing :)"
}

if [ $(basename $PWD)  != dotfiles ]; then
   echo "not inside the directory"
   exit 1
fi 

create_env
copy_cfg

# scan all font directories
fc-cache

