#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         1
bspc config border_radius	 9
#bspc config normal_border_color "#343434"
#bspc config active_border_color "#212121"

bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a Discord desktop='^4' follow=on
# Put the discord updater on the same workspace
bspc rule -a Discord Updater desktop='^4'


# Startup
xsetroot -cursor_name left_ptr
picom --experimental-backends --backend glx -b &
dunst &
nitrogen --restore &
$HOME/.config/polybar/launch.sh


